# Generated by Django 6.1.1 on 2026-10-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_whatsapp', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('height_cm', models.IntegerField(help_text='Height in cm')),
                ('city', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('languages', models.CharField(help_text='e.g. English, French, Yoruba', max_length=200)),
                ('experience_years', models.CharField(max_length=50)),
                ('experience_summary', models.TextField()),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted for Audition'), ('accepted', 'Accepted into Academy'), ('active', 'Active Protocol Officer'), ('rejected', 'Not Selected')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('corporate', 'Corporate'), ('wedding', 'Wedding'), ('conference', 'Conference'), ('government', 'Government & Diplomatic'), ('entertainment', 'Entertainment & Gala'), ('exhibition', 'Exhibition & Expo')], max_length=50)),
                ('date_held', models.DateField()),
                ('location', models.CharField(help_text='e.g. Eko Convention Centre, Victoria Island', max_length=255)),
                ('city', models.CharField(default='Lagos, Nigeria', max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('planner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('crew_deployed', models.IntegerField(default=20, help_text='Number of ushers / protocol officers')),
                ('services_provided', models.CharField(help_text='e.g. VIP Protocol • Digital Registration • Red Carpet • Hall Ushering', max_length=300)),
                ('summary', models.TextField()),
                ('highlight_result', models.CharField(help_text='Key accomplishment or metric', max_length=255)),
                ('image_url', models.CharField(max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-date_held'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('events', 'Event Highlights'), ('team', 'Our Team & Officers'), ('uniforms', 'Uniform Lookbook'), ('protocol', 'VIP Protocol'), ('conferences', 'Conferences & Summits'), ('weddings', 'Luxury Weddings'), ('bts', 'Behind The Scenes')], default='events', max_length=50)),
                ('image_url', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_whatsapp', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=250)),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_duration_hours', models.IntegerField(default=8)),
                ('event_location', models.CharField(default='Lagos, Nigeria', max_length=150)),
                ('venue_name', models.CharField(max_length=250)),
                ('expected_guests', models.CharField(max_length=100)),
                ('services_required', models.TextField(help_text='Comma-separated selected services')),
                ('crew_count', models.IntegerField(default=10)),
                ('gender_preference', models.CharField(default='Balanced Mix', max_length=100)),
                ('uniform_preference', models.CharField(default='Classic Black-Tie Tuxedo & Gown', max_length=150)),
                ('special_requirements', models.TextField(blank=True)),
                ('estimated_cost_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_cost_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('new', 'New Inquiry'), ('contacted', 'Contacted / Proposal Sent'), ('confirmed', 'Confirmed & Booked'), ('completed', 'Event Completed'), ('archived', 'Archived')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('protocol', 'VIP & Diplomatic Protocol'), ('ushering', 'Event Ushering & Guest Experience'), ('corporate', 'Corporate & Conference Management'), ('specialist', 'Specialist & Logistics Coordination')], default='ushering', max_length=50)),
                ('short_description', models.TextField(help_text='Short teaser for cards and hero previews')),
                ('full_description', models.TextField(help_text='In-depth breakdown of the service')),
                ('icon_name', models.CharField(default='crown', help_text='Lucide icon name e.g. crown, shield-check, users, award, mic', max_length=50)),
                ('deliverables', models.TextField(help_text='Newline-separated list of what is included')),
                ('suitable_events', models.TextField(help_text='Newline-separated list of suitable event types')),
                ('uniform_recommendations', models.CharField(default='Corporate Black-Tie or Luxury Velvet', max_length=255)),
                ('badge_text', models.CharField(blank=True, help_text="e.g. 'Most Requested' or 'VIP Exclusive'", max_length=100, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_role_company', models.CharField(help_text='e.g. Lead Planner, Aurora Luxury Weddings', max_length=200)),
                ('event_name', models.CharField(max_length=200)),
                ('quote', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('avatar_url', models.CharField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniformStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tag', models.CharField(help_text='e.g. VIP Galas & Red Carpets', max_length=100)),
                ('description', models.TextField()),
                ('gender', models.CharField(default='Unisex / Male & Female', max_length=50)),
                ('image_url', models.CharField(max_length=500)),
                ('color_palette', models.CharField(default='Imperial Gold & Obsidian Black', max_length=150)),
            ],
        ),
    ]
