# Generated by Django 6.1.1 on 2026-10-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='crown', help_text='Lucide icon name e.g. crown, shield-check, lock, clock, sparkles, languages', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_hero_badge', models.CharField(default='Our Story & Ethos', max_length=150)),
                ('about_hero_title', models.CharField(default='Redefining African Event Hospitality With Unmatched Poise.', max_length=255)),
                ('about_hero_subtitle', models.TextField(default='Founded on the conviction that event staffing should be a disciplined craft of diplomatic excellence, executive etiquette, and genuine African warmth.')),
                ('about_story_title', models.CharField(default='The Poised Story: From Event Staffing to Protocol Authority', max_length=255)),
                ('about_story_paragraph_1', models.TextField(default='The Poised Crew was established to bridge a critical gap in the luxury and corporate event industry: the need for impeccably trained, highly punctual, and intellectually sharp protocol officers who can effortlessly navigate both cultural traditions and strict diplomatic decorum.')),
                ('about_story_paragraph_2', models.TextField(default='Whether handling the accreditation of 3,000 international delegates at an African energy summit or orchestrating royal family protocol at a multi-day wedding, our crew brings calmness, precision, and commanding elegance to every engagement.')),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_statement', models.TextField(default="To provide flawless hospitality and protocol choreography that protects our clients' prestige and creates an unforgettable guest experience.")),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_statement', models.TextField(default="To be Africa's benchmark institution for diplomatic protocol, luxury event ushering, and executive hospitality leadership.")),
                ('academy_title', models.CharField(default='The Poised Academy', max_length=150)),
                ('academy_description', models.TextField(default='Over 400 hours of annual protocol & etiquette drill sessions')),
                ('academy_image_url', models.CharField(default='https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1000&q=80', max_length=500)),
                ('hero_badge', models.CharField(default='Excellence in Event Protocol & Luxury Hospitality', max_length=150)),
                ('hero_title', models.CharField(default='Where Regal Poise Meets Diplomatic Precision.', max_length=255)),
                ('hero_subtitle', models.TextField(default='Transforming conferences, high-society weddings, state banquets, and red-carpet galas into seamless, unforgettable experiences across Africa.')),
                ('hero_guarantee_1', models.CharField(default='100% Punctuality Guarantee', max_length=100)),
                ('hero_guarantee_2', models.CharField(default='Certified Etiquette & Protocol', max_length=100)),
                ('hero_guarantee_3', models.CharField(default='Bespoke Attire Customization', max_length=100)),
                ('stat_events_count', models.CharField(default='500+', max_length=50)),
                ('stat_events_label', models.CharField(default='Events Executed', max_length=100)),
                ('stat_officers_count', models.CharField(default='120+', max_length=50)),
                ('stat_officers_label', models.CharField(default='Vetted Protocol Officers', max_length=100)),
                ('stat_punctuality_rate', models.CharField(default='99.9%', max_length=50)),
                ('stat_punctuality_label', models.CharField(default='On-Time Deployment', max_length=100)),
                ('stat_summits_count', models.CharField(default='15+', max_length=50)),
                ('stat_summits_label', models.CharField(default='Diplomatic Summits', max_length=100)),
                ('company_name', models.CharField(default='The Poised Crew', max_length=150)),
                ('tagline', models.CharField(default='Luxury Event Ushering & VIP Protocol Agency', max_length=255)),
                ('phone_display', models.CharField(default='0705 185 1600', max_length=50)),
                ('whatsapp_number', models.CharField(default='2347051851600', max_length=50)),
                ('email_address', models.EmailField(default='thepoisedcrew@gmail.com', max_length=254)),
                ('office_address', models.CharField(default='Benin City, Edo State', max_length=255)),
                ('instagram_handle', models.CharField(blank=True, default='@thepoisedcrew', max_length=100)),
                ('cta_banner_title', models.CharField(default='Elevate Your Next High-Profile Event With The Poised Crew', max_length=255)),
                ('cta_banner_subtitle', models.TextField(default="From royal ceremonies and political summits to luxury society weddings, reserve Africa's most distinguished protocol and ushering professionals.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Content & Settings',
                'verbose_name_plural': 'Website Content & Settings',
            },
        ),
    ]
