# Generated by Django 6.1.1 on 2026-10-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_corevalue_sitecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventportfolio',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload portfolio photo (auto-compressed to WebP)', null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload gallery image (auto-compressed to WebP)', null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='academy_image',
            field=models.ImageField(blank=True, help_text='Upload academy/showcase photo (auto-compressed to WebP)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload client/planner photo (auto-compressed to WebP)', null=True, upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='uniformstyle',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload uniform photo (auto-compressed to WebP)', null=True, upload_to='uniforms/'),
        ),
        migrations.AlterField(
            model_name='eventportfolio',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='academy_image_url',
            field=models.CharField(blank=True, default='https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1000&q=80', max_length=500),
        ),
        migrations.AlterField(
            model_name='uniformstyle',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
